import React from "react";
import { SampleScript, SamplesTab } from "components/common/samples/partials/samplesTypes";
import { createMethodsTab, createSampleScriptsTab } from "components/common/samples/partials/samplesTabFactories";
import { GenAiMethodsNotice, contextScriptMethodGroups, updateScriptMethodGroups } from "./editGenAiTaskMethodsData";
import { dedent } from "components/utils/dedent";

const contextScriptSamples: SampleScript[] = [
    {
        title: "Generate context objects",
        description:
            "Iterate over the source document and emit one context object per item. Every context object becomes its own request to the model, and the script must call ai.genContext at least once.",
        language: "javascript",
        script: dedent`
            for(const comment of this.Comments)  // 'this' is the source document
            {
                // Call 'ai.genContext' to generate a context object for each comment.
                // The custom object passed to this method defines the structure of the context object.
                ai.genContext({
                    Text: \`Blog post topic: \${this.Topic}. Comment: \${comment.Text}\`,
                    AuthorName: comment.Author,
                    CommentId: comment.Id
                });
            }
        `,
    },
    {
        title: "With attachments",
        description:
            "Attach document attachments (images, text files) to the generated context objects. A missing attachment comes back as null, which the withXxx methods accept, so no guard is needed.",
        language: "javascript",
        script: dedent`
            for(const comment of this.Comments)
            {
                ai.genContext({ Id: comment.Id })
                    .withPng(loadAttachment("heart.png"))
                    .withText(loadAttachment("transactions.csv"))
                    .withText(loadAttachment("text.txt"));
            }
        `,
    },
    {
        title: "With inline Base64 data",
        description:
            "Attachments do not have to come from the document. Any Base64 string works, so data built or stored inside the document can be sent to the model directly.",
        language: "javascript",
        script: dedent`
            // Any of the withXxx methods accepts a Base64 string instead of an attachment reference.
            // Pass the payload only, with no "data:image/png;base64," prefix.
            const logo = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8DwHwAFAAH/q842iQAAAABJRU5ErkJggg==";

            ai.genContext({ Topic: this.Topic })
                .withPng(logo)
                .withText(this.Transcript);
        `,
    },
];

const promptSamples: SampleScript[] = [
    {
        title: "Spam detection prompt",
        description:
            "The instruction sent with every context object. Describe the task and the criteria; the shape of the answer comes from the sample response object below, not from the prompt.",
        language: "plaintext",
        whiteSpace: "pre-wrap",
        script: "Check if the following blog post comment is spam or not. A spam comment typically includes irrelevant or promotional content, excessive links, misleading information, or is written with the intent to manipulate search rankings or advertise products/services. Consider the language, intent, and relevance of the comment to the blog post topic.",
    },
];

const sampleObjectSamples: SampleScript[] = [
    {
        title: "Sample response object",
        description:
            'The shape of the object the model should return. Values are not example data: every string value is turned into the JSON schema "description" for that field, so write it as an instruction to the model. Booleans and numbers only give the type, so put any guidance for them in the prompt.',
        language: "json",
        script: dedent`
            {
                "IsCommentSpam": true,
                "Reason": "Concise reason for why this comment was marked as spam or ham"
            }
        `,
    },
];

const updateScriptSamples: SampleScript[] = [
    {
        title: "Update the source document",
        description:
            "React to the model output: remove spam comments and archive them in a separate collection. The script runs once per context object, so it has to find the part of the document that $input came from.",
        language: "javascript",
        script: dedent`
            // $input - the model input (generated by ai.genContext())
            // $output - the model output
            // this - the source document

            if ($output.IsCommentSpam) {
                // Update the source document. Check the index: findIndex returns -1 when the comment
                // is already gone, and splice(-1, 1) would drop the last comment instead.
                const idx = this.Comments.findIndex(comment => comment.Id == $input.CommentId);
                if (idx !== -1) {
                    this.Comments.splice(idx, 1); // remove comment
                }

                // Can create new documents. Use a different id than the source document:
                // the task writes 'this' back at the end of the run and would overwrite it.
                const newDocument = { "Comment": $input.Text, "Reason": $output.Reason,
                    "@metadata": { "@collection": "spamComments" } };
                put(id(this) + "/spam/", newDocument);
            }
        `,
    },
];

const jsonSchemaSamples: SampleScript[] = [
    {
        title: "Sample JSON schema",
        description:
            'The schema that will be sent to the model, describing the expected response object. A response schema is wrapped in name / strict / schema; when RavenDB derives it from the sample object it also derives a unique name, so "some-name" only matters if you write the schema by hand. A schema you provide here takes precedence over the sample object.',
        language: "json",
        script: dedent`
            {
                "name": "some-name",
                "strict": true,
                "schema": {
                    "type": "object",
                    "properties": {
                        "IsCommentSpam": {
                            "type": "boolean"
                        },
                        "Reason": {
                            "type": "string",
                            "description": "Concise reason for why this comment was marked as spam or ham"
                        }
                    },
                    "required": [
                        "IsCommentSpam",
                        "Reason"
                    ],
                    "additionalProperties": false
                }
            }
        `,
    },
];

const queryToolParametersSamples: SampleScript[] = [
    {
        title: "Query parameters",
        description:
            "Instruct the LLM what value to supply for each query parameter. Only declare parameters the context objects do not already provide; anything present in the context is filled in from there.",
        language: "json",
        script: dedent`
            {
                "country": "Provide the country to which the order was shipped.",
                "company": "Provide the company that placed this order."
            }
        `,
    },
    {
        title: "Vector search parameters",
        description: "Parameters for a semantic search query.",
        language: "json",
        script: dedent`
            {
                "searchTerm": "Provide the name of a product to search for similar items.",
                "similarityLevel": "Provide the similarity level to apply in the search."
            }
        `,
    },
    {
        title: "No parameters",
        description: "Use an empty object when the query takes no parameters.",
        language: "json",
        script: `{}`,
    },
];

const queryToolQuerySamples: SampleScript[] = [
    {
        title: "Filter by context parameters",
        description:
            "A parameter that exists as a property of the context object is filled in from the context. Anything else has to be declared in the sample parameters object below, for the model to supply.",
        language: "rql",
        script: dedent`
            from "Orders"
            where ShipTo.Country == $country and Company == $company
            select ShipTo.Country as Country, Company, Lines, OrderedAt
        `,
    },
    {
        title: "Semantic search over a collection",
        description: "Let the model look for products similar to a term it chooses.",
        language: "rql",
        script: dedent`
            from "Products"
            where vector.search(embedding.text(Name), $searchTerm, $similarityLevel)
            select Name, PricePerUnit
        `,
    },
    {
        title: "Query a static index",
        description:
            "Indexed queries work too, and are the better choice for a tool the model may call often. Project only the fields the model needs, to keep the tool result small.",
        language: "rql",
        script: dedent`
            from index "Orders/ByCompany"
            where Company == $company
            select Company, Count, Total
        `,
    },
];

const queryToolParametersSchemaSamples: SampleScript[] = [
    {
        title: "Parameters JSON schema",
        description:
            "The schema generated from the sample parameters object. A tool parameters schema is the bare object, with no name / strict wrapper: that wrapper belongs only to the response schema in the previous step.",
        language: "json",
        script: dedent`
            {
                "type": "object",
                "properties": {
                    "country": {
                        "type": "string",
                        "description": "Provide the country to which the order was shipped."
                    },
                    "company": {
                        "type": "string",
                        "description": "Provide the company that placed this order."
                    }
                },
                "required": [
                    "country",
                    "company"
                ],
                "additionalProperties": false
            }
        `,
    },
];

export const contextScriptSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(contextScriptSamples),
    createMethodsTab(contextScriptMethodGroups, { language: "javascript", notice: <GenAiMethodsNotice /> }),
];
export const promptSamplesTabs: SamplesTab[] = [createSampleScriptsTab(promptSamples, { label: "Sample prompt" })];
export const sampleObjectSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(sampleObjectSamples, { label: "Sample object" }),
];
export const jsonSchemaSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(jsonSchemaSamples, { label: "Sample schema" }),
];
export const updateScriptSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(updateScriptSamples),
    createMethodsTab(updateScriptMethodGroups, { language: "javascript", notice: <GenAiMethodsNotice /> }),
];
export const queryToolQuerySamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(queryToolQuerySamples, { label: "Sample queries" }),
];
export const queryToolParametersSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(queryToolParametersSamples, { label: "Sample object" }),
];
export const queryToolParametersSchemaSamplesTabs: SamplesTab[] = [
    createSampleScriptsTab(queryToolParametersSchemaSamples, { label: "Sample schema" }),
];
